platform :ios, '8.0'
target 'LastTry' do
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
pod 'GoogleMaps'
pod 'Firebase'
pod 'Firebase/Database'
  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

end